name: pixberts-new
channels:
  - conda-forge
  - pytorch
  - pytorch3d
  - nvidia
  - pyg
dependencies:
  - python=3.10.14
  - pytorch:pytorch=2.1.2
  - pytorch:pytorch-cuda=11.8
  # - llvm-openmp<16
  - einops=0.6.1
  - pytorch-lightning
  - pandas
  - dm-tree=0.1.7
  - diskcache=5.4.0
  - fire=0.5.0
  - numpy=1.26.4
  - scikit-learn=1.3.0
  - pip
  - gpustat
  - wandb
  - easydict=1.9
  - matplotlib=3.8.0
  - pytorch-scatter
  - pytorch_geometric
  - pytorch-sparse
  - pytorch-cluster
  - pip:
    - biopython==1.84
    - fair-esm
    - tree==0.2.4
    - seaborn==0.13.2
    - triton==2.1.0
    - flash-attn==2.5.9
    - biotite==0.41.2
    - cpdb-protein==0.2.0
    # - torch_cluster==1.6.3
    # - -e git+https://github.com/lbcb-sci/RiNALMo.git
    - -i https://pypi.tuna.tsinghua.edu.cn/simple