resume: null
model: 
  model_type: gat
  output_dim: 1
  in_dim: 41
  node_dim: 128
  depth: 3
  hidden_dims:
    - 128
    - 128
    - 128

train:
  max_iters: 30_000
  val_freq: 1000
  seed: 2024
  max_grad_norm: 100.0
  optimizer:
    type: adam
    lr: 1.e-4
    weight_decay: 0.0
    beta1: 0.9
    beta2: 0.999
  scheduler:
    type: plateau
    factor: 0.8
    patience: 5
    min_lr: 1.e-6